version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app # ローカルをコンテナ内にマウント
    image: frontend
    container_name: frontend
    command: sh -c "npm run dev"
    ports:
      - "5173:5173"
      - "4173:4173"
    stdin_open: true
  # ============
  # 開発用
  # ============
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8081:8080"
    container_name: go-backend-dev
    tty: true
    volumes:
      - ./backend:/app
  # ============
  # 本番用
  # ============
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    platform: linux/amd64
    image: go-backend-prod
    ports:
      - "8081:8080"
    container_name: go-backend-prod
